# Generated by Django 5.0 on 2023-12-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chest', '0002_alter_diagnosis_user_diagnosis_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='doctor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
